[build]
builder = "nixpacks"
buildCommand = "cd server && npm install"
watchPatterns = ["server/**"]

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[variables]
PORT = "3001" 