param(
    [Parameter(Mandatory = $true)]
    [string]$NgrokUrl
)

Write-Host "🔧 Updating ngrok URL in frontend configuration..." -ForegroundColor Green
Write-Host ""

# Ensure the URL starts with https://
if (-not $NgrokUrl.StartsWith("https://")) {
    $NgrokUrl = "https://$NgrokUrl"
}

# Remove trailing slash if present
$NgrokUrl = $NgrokUrl.TrimEnd('/')

Write-Host "📌 Setting API URL to: $NgrokUrl" -ForegroundColor Yellow

# Create or update .env.local file in client directory
$envFilePath = Join-Path $PSScriptRoot "client\.env.local"
$envContent = @"
# Client Environment Variables for Local Development
# Auto-generated by update-ngrok-url.ps1

# API URL - Your ngrok tunnel URL
VITE_API_URL=$NgrokUrl

# Supabase Configuration
VITE_SUPABASE_URL=https://yqsumodzyahvxywwfpnc.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxc3Vtb2R6eWFodnl5d3dmcG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NDQzNDAsImV4cCI6MjA1MjUyMDM0MH0.qjSUPPm3dN-96F6x7LB-FnE2O7aAVUJNgPRmkVUxUTU
"@

# Write the file
$envContent | Out-File -FilePath $envFilePath -Encoding UTF8 -Force

Write-Host "✅ Created/Updated: $envFilePath" -ForegroundColor Green
Write-Host ""

# Test the ngrok connection
Write-Host "🔍 Testing ngrok connection..." -ForegroundColor Yellow
try {
    $healthCheck = Invoke-RestMethod -Uri "$NgrokUrl/health" -Method Get -Headers @{
        "ngrok-skip-browser-warning" = "true"
    }
    Write-Host "✅ Health check passed: $($healthCheck.status)" -ForegroundColor Green
}
catch {
    Write-Host "❌ Health check failed: $_" -ForegroundColor Red
    Write-Host "   Make sure your backend server is running and ngrok is connected" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "📝 Next steps:" -ForegroundColor Cyan
Write-Host "   1. Make sure your backend server is running (npm start in server directory)" -ForegroundColor White
Write-Host "   2. Make sure ngrok is running and connected to port 3001" -ForegroundColor White
Write-Host "   3. Restart your frontend development server (npm run dev in client directory)" -ForegroundColor White
Write-Host "   4. The frontend will now use: $NgrokUrl" -ForegroundColor White
Write-Host ""

Read-Host "Press Enter to exit" 