# serverless.yml

service: mjd-backend-4
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'prod'}
  environment:
    NODE_ENV: ${opt:stage, 'production'}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY}
    S3_BUCKET_NAME: ${self:custom.s3BucketName}

  # IAM permissions for Lambda
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - "arn:aws:s3:::${self:custom.s3BucketName}"
            - "arn:aws:s3:::${self:custom.s3BucketName}/*"

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      allowCredentials: false
    payload: "2.0"

functions:
  api:
    handler: handler.handler
    timeout: 900
    memorySize: 2048
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

plugins:
  - serverless-dotenv-plugin

package:
  individually: false
  patterns:
    - "!node_modules/**"
    - "!.git/**"
    - "!.env*"
    - "!README.md"
    - "!.gitignore"
    - "handler.js"
    - "app.js"
    - "routes/**"
    - "services/**"
    - "temp/**"
    - "output/**"

custom:
  s3BucketName: mjd-backend-4-${self:provider.stage}-uploads
  dotenv:
    path: ./.env
    include:
      - SUPABASE_URL
      - SUPABASE_ANON_KEY
      - SUPABASE_SERVICE_ROLE_KEY
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

resources:
  Resources:
    S3BucketUploads:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
  Outputs:
    S3BucketName:
      Value:
        Ref: S3BucketUploads
      Export:
        Name: ${self:service}-${self:provider.stage}-S3BucketName
